import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import lolwalpaper from '../imagenes/lolwalpaper.png'
import starcraft from '../imagenes/starcraft.jpg'
import gearogWar from '../imagenes/gearofWar.jpg'
import Halo from '../imagenes/halo.jpeg'

export default function Apuestas() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Mi dApp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Bienvenido a GamePot
        </h1>

        <p className={styles.description}>
          Seccion donde puesde apostar a tu equipos o jugadores favoritos{' '}
        </p>

        <div className={styles.grid}>
          <a href="http://localhost:3000/gamepot1" className={styles.card}>
            <h2>LOL &rarr;</h2>
            <Image
                src={lolwalpaper}
                alt=''
                width={1920 / 8}
                height={1080 / 8}
            />
            <p></p>
          </a>
          <a href="http://localhost:3000/gamepot2" className={styles.card}>
            <h2>starcraft &rarr;</h2>
            <Image
                src={starcraft}
                alt=''
                width={1920 / 8}
                height={1080 / 8}
            />
            <p></p>
          </a>
          <a href="http://localhost:3000/gamepot3" className={styles.card}>
            <h2>Gear of War &rarr;</h2>
            <Image
                src={gearogWar}
                alt=''
                width={1920 / 8}
                height={1080 / 8}
            />
            <p></p>
          </a>
          <a href="http://localhost:3000/gamepot4" className={styles.card}>
            <h2>Halo &rarr;</h2>
            <Image
                src={Halo}
                alt=''
                width={1920 / 8}
                height={1080 / 8}
            />
            <p></p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}