import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Mi dApp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">GameFuse</a>
        </h1>

        <p className={styles.description}>
          Lugar donde tus habilidades te hacen ganar{' '}
        </p>

        <div className={styles.grid}>
          <a href="http://localhost:3000/torneos" className={styles.card}>
            <h2>Torneos &rarr;</h2>
            <p>Lugar competitivo donde puedes poner tus habilidades a prueba</p>
          </a>

          <a href="http://localhost:3000/apuestas" className={styles.card}>
            <h2>Apuestas &rarr;</h2>
            <p>Lugar competitivo donde puedes poner tus conocimientos a prueba</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>FAQ &rarr;</h2>
            <p>Para aclarar tus dudas</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
            className={styles.card}
          >
            <h2>Nosotros &rarr;</h2>
            <p>
              Conocemos un poco mas en nuestra aventura
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}